#pragma once

#include <map>
#include <string>

// linux alt?
#define DIRECTORY		"C:/Windows/Fonts/"
#define FALLBACK_FONT	"data/fonts/consolab.ttf"

using namespace std;

struct Font;

class Fonts {
	public:
		static map<pair<string, int>, Font*> fonts;
		static map<pair<string, int>, bool> fonts_is_custom_temp;

		static void cleanup();
		static void load_font(const string&, int, bool = false);
		static Font* get_font(const string&, int, bool = false);
		static pair<string, int> get_properties(Font*);
};

#define	ARIAL						"arial.ttf"
#define	ARIAL_BOLD					"arialbd.ttf"
#define	ARIAL_BOLD_ITALIC			"arialbi.ttf"
#define	ARIAL_ITALIC				"ariali.ttf"
#define	ARIAL_BLACK					"ariblk.ttf"
#define	BAHNSCHRIFT					"bahnschrift.ttf"
#define	CALIBRI						"calibri.ttf"
#define	CALIBRI_BOLD				"calibrib.ttf"
#define	CALIBRI_ITALIC				"calibrii.ttf"
#define	CALIBRI_LIGHT				"calibril.ttf"
#define	CALIBRI_LIGHT_ITALIC		"calibrili.ttf"
#define	CALIBRI_BOLD_ITALIC			"calibriz.ttf"
#define	CAMBRIA_BOLD				"cambriab.ttf"
#define	CAMBRIA_ITALIC				"cambriai.ttf"
#define	CAMBRIA_BOLD_ITALIC			"cambriaz.ttf"
#define	CANDARA						"Candara.ttf"
#define	CANDARA_BOLD				"Candarab.ttf"
#define	CANDARA_ITALIC				"Candarai.ttf"
#define	CANDARA_LIGHT				"Candaral.ttf"
#define	CANDARA_LIGHT_ITALIC		"Candarali.ttf"
#define	CANDARA_BOLD_ITALIC			"Candaraz.ttf"
#define	COMIC_SANS_MS				"comic.ttf"
#define	COMIC_SANS_MS_BOLD			"comicbd.ttf"
#define	COMIC_SANS_MS_ITALIC		"comici.ttf"
#define	COMIC_SANS_MS_BOLD_ITALIC	"comicz.ttf"
#define	CONSOLAS					"consola.ttf"
#define	CONSOLAS_BOLD				"consolab.ttf"
#define	CONSOLAS_ITALIC				"consolai.ttf"
#define	CONSOLAS_BOLD_ITALIC		"consolaz.ttf"
#define	CONSTANTIA					"constan.ttf"
#define	CONSTANTIA_BOLD				"constanb.ttf"
#define	CONSTANTIA_ITALIC			"constani.ttf"
#define	CONSTANTIA_BOLD_ITALIC		"constanz.ttf"
#define	CORBEL						"corbel.ttf"
#define	CORBEL_BOLD					"corbelb.ttf"
#define	CORBEL_ITALIC				"corbeli.ttf"
#define	CORBEL_LIGHT				"corbell.ttf"
#define	CORBEL_LIGHT_ITALIC			"corbelli.ttf"
#define	CORBEL_BOLD_ITALIC			"corbelz.ttf"
#define	COURIER_NEW					"cour.ttf"
#define	COURIER_NEW_BOLD			"courbd.ttf"
#define	COURIER_NEW_BOLD_ITALIC		"courbi.ttf"
#define	COURIER_NEW_ITALIC			"couri.ttf"
#define	EBRIMA						"ebrima.ttf"
#define	EBRIMA_BOLD					"ebrimabd.ttf"
#define	FRANKLIN_GOTHIC_MEDIUM		"framd.ttf"
#define	FRANKLIN_GOTHIC_MEDIUM_ITALIC "framdit.ttf"
#define	GABRIOLA					"Gabriola.ttf"
#define	GADUGI						"gadugi.ttf"
#define	GADUGI_BOLD					"gadugib.ttf"
#define	GEORGIA						"georgia.ttf"
#define	GEORGIA_BOLD				"georgiab.ttf"
#define	GEORGIA_ITALIC				"georgiai.ttf"
#define	GEORGIA_BOLD_ITALIC			"georgiaz.ttf"
#define	MICROSOFT_HIMALAYA			"himalaya.ttf"
#define	HOLOLENS_MDL2_ASSETS		"holomdl2.ttf"
#define	IMPACT						"impact.ttf"
#define	INK_FREE					"Inkfree.ttf"
#define	JAVANESE_TEXT				"javatext.ttf"
#define	LATO_BOLD					"LatoWeb-Bold.ttf"
#define	LATO_BOLD_ITALIC			"LatoWeb-BoldItalic.ttf"
#define	LATO_ITALIC					"LatoWeb-Italic.ttf"
#define	LATO_LIGHT					"LatoWeb-Light.ttf"
#define	LATO_LIGHT_ITALIC			"LatoWeb-LightItalic.ttf"
#define	LATO						"LatoWeb-Regular.ttf"
#define	LATO_SEMIBOLD				"LatoWeb-Semibold.ttf"
#define	LATO_SEMIBOLD_ITALIC		"LatoWeb-SemiboldItalic.ttf"
#define	LEELAWADEE_UI_BOLD			"LeelaUIb.ttf"
#define	LEELAWADEE_UI				"LeelawUI.ttf"
#define	LEELAWADEE_UI_SEMILIGHT		"LeelUIsl.ttf"
#define	LUCIDA_CONSOLE				"lucon.ttf"
#define	LUCIDA_SANS_UNICODE			"l_10646.ttf"
#define	MARLETT						"marlett.ttf"
#define	MICROSOFT_SANS_SERIF		"micross.ttf"
#define	MYANMAR_TEXT				"mmrtext.ttf"
#define	MYANMAR_TEXT_BOLD			"mmrtextb.ttf"
#define	MONGOLIAN_BAITI				"monbaiti.ttf"
#define	MICROSOFT_YI_BAITI			"msyi.ttf"
#define	MV_BOLI						"mvboli.ttf"
#define	NIRMALA_UI					"Nirmala.ttf"
#define	NIRMALA_UI_BOLD				"NirmalaB.ttf"
#define	NIRMALA_UI_SEMILIGHT		"NirmalaS.ttf"
#define	MICROSOFT_NEW_TAI_LUE		"ntailu.ttf"
#define	MICROSOFT_NEW_TAI_LUE_BOLD	"ntailub.ttf"
#define	PALATINO_LINOTYPE			"pala.ttf"
#define	PALATINO_LINOTYPE_BOLD		"palab.ttf"
#define	PALATINO_LINOTYPE_BOLD_ITALIC "palabi.ttf"
#define	PALATINO_LINOTYPE_ITALIC	"palai.ttf"
#define	MICROSOFT_PHAGSPA			"phagspa.ttf"
#define	MICROSOFT_PHAGSPA_BOLD		"phagspab.ttf"
#define	SEGOE_MDL2_ASSETS			"segmdl2.ttf"
#define	SEGOE_PRINT					"segoepr.ttf"
#define	SEGOE_PRINT_BOLD			"segoeprb.ttf"
#define	SEGOE_SCRIPT				"segoesc.ttf"
#define	SEGOE_SCRIPT_BOLD			"segoescb.ttf"
#define	SEGOE_UI					"segoeui.ttf"
#define	SEGOE_UI_BOLD				"segoeuib.ttf"
#define	SEGOE_UI_ITALIC				"segoeuii.ttf"
#define	SEGOE_UI_LIGHT				"segoeuil.ttf"
#define	SEGOE_UI_SEMILIGHT			"segoeuisl.ttf"
#define	SEGOE_UI_BOLD_ITALIC		"segoeuiz.ttf"
#define	SEGOE_UI_BLACK				"seguibl.ttf"
#define	SEGOE_UI_BLACK_ITALIC		"seguibli.ttf"
#define	SEGOE_UI_EMOJI				"seguiemj.ttf"
#define	SEGOE_UI_HISTORIC			"seguihis.ttf"
#define	SEGOE_UI_LIGHT_ITALIC		"seguili.ttf"
#define	SEGOE_UI_SEMIBOLD			"seguisb.ttf"
#define	SEGOE_UI_SEMIBOLD_ITALIC	"seguisbi.ttf"
#define	SEGOE_UI_SEMILIGHT_ITALIC	"seguisli.ttf"
#define	SEGOE_UI_SYMBOL				"seguisym.ttf"
#define	SYLFAEN						"sylfaen.ttf"
#define	SYMBOL						"symbol.ttf"
#define	TAHOMA						"tahoma.ttf"
#define	TAHOMA_BOLD					"tahomabd.ttf"
#define	MICROSOFT_TAI_LE			"taile.ttf"
#define	MICROSOFT_TAI_LE_BOLD		"taileb.ttf"
#define	TIMES_NEW_ROMAN				"times.ttf"
#define	TIMES_NEW_ROMAN_BOLD		"timesbd.ttf"
#define	TIMES_NEW_ROMAN_BOLD_ITALIC	"timesbi.ttf"
#define	TIMES_NEW_ROMAN_ITALIC		"timesi.ttf"
#define	TREBUCHET_MS				"trebuc.ttf"
#define	TREBUCHET_MS_BOLD			"trebucbd.ttf"
#define	TREBUCHET_MS_BOLD_ITALIC	"trebucbi.ttf"
#define	TREBUCHET_MS_ITALIC			"trebucit.ttf"
#define	UNISPACE					"unispace bd.ttf"
#define	VERDANA						"verdana.ttf"
#define	VERDANA_BOLD				"verdanab.ttf"
#define	VERDANA_ITALIC				"verdanai.ttf"
#define	VERDANA_BOLD_ITALIC			"verdanaz.ttf"
#define	WEBDINGS					"webdings.ttf"
#define	WINGDINGS					"wingding.ttf"

#define INCONSOLATA_REGULAR			"Inconsolata-Regular.ttf"
#define INCONSOLATA_BOLD			"Inconsolata-Bold.ttf"
